### ISSUE TITLE
Issues with installation.

### ISSUE THREAD

**Issue by SoulxSlayer** [THtianhao/ComfyUI-Portrait-Maker#1]
As mentioned in your installation notes, this requires `aliyun-python-sdk-core` for it to function but installing it gives that error. I tried to use the solutions but nothing worked. Installed ` opendatalab==0.0.9` and `openmim` but that totally bricked my ComfyUI. Is there a particular way to make it work? What am I missing?

**Comment by THtianhao** [comment]
You can use` pip -m venv venv` to create a virtual environment. After switching to this virtual environment, install ComfyUI and project dependencies` requirement.txt` You can also wait for modelscope to fix this problem and reinstall this plug-in. It is expected to be fixed in a few days.

**Comment by SoulxSlayer** [comment]
Ok! Thanks for the help!

**Comment by Kinglord** [comment]
Hi, just wanted to say that this isn't really a good solution for people running standalone comfy because they won't be using venvs. I'm going to open an issue so everyone that does will at know this custom node won't work for them yet.
