### ISSUE TITLE
Always load the models

### ISSUE THREAD

**Issue by lunatico67** [THtianhao/ComfyUI-Portrait-Maker#14]
Hi! 
I don't like checkpoint and the lora that portrait maker chooses, I prefer to load others. 
The problem is that every time I open Comfyui it loads them automatically, to avoid that I have to move the Comfyui portrait maker folder from Comfyui-custom nodes to another place on my computer so that comfyui doesn't detect it and once opened move it back to its custom nodes folder to be able to use it. 
Is there no way to disable the checkpoint and lora models to load from portrait maker every time I open comfyui?

**Comment by THtianhao** [comment]
okay, I'll resolve it tomorrow

**Comment by lunatico67** [comment]
Thanks Taylor

**Comment by THtianhao** [comment]
Base Models will no longer be downloaded
