### ISSUE TITLE
Help! An error is occur

### ISSUE THREAD

**Issue by xuepeilei** [THtianhao/ComfyUI-Portrait-Maker#16]
![image](https://github.com/THtianhao/ComfyUI-Portrait-Maker/assets/16931942/15e9fa94-6ad4-4170-a332-5481ed10686f)
![image](https://github.com/THtianhao/ComfyUI-Portrait-Maker/assets/16931942/3b047dca-f398-4587-8d49-8c3862e0c925)

**Comment by xuepeilei** [comment]
![image](https://github.com/THtianhao/ComfyUI-Portrait-Maker/assets/16931942/3d9acd09-2d6e-44de-9617-79252d22a6fc)

**Comment by THtianhao** [comment]
please check your cuda and cudnn environment
