### ISSUE TITLE
准备运行起来，思路很棒！提几个优化项

### ISSUE THREAD

**Issue by vvip2u** [THtianhao/ComfyUI-Portrait-Maker#17]
准备运行起来，思路很棒！

提几个建议
- 不要启用的时候直接就下载，检查`extra_model_paths.yaml`路径是否指向向了SD路径
- 也有可能别人的模型已经下载名字不一样，用MD5检查下是否已经文件存在，存在就不重复下载

**Comment by THtianhao** [comment]
好的谢谢，其实这块是考虑到新手使用的关系才这么做的
