### ISSUE TITLE
文件管理混乱

### ISSUE THREAD

**Issue by merlinmxn** [THtianhao/ComfyUI-Portrait-Maker#21]
控图模型和预处理器模型一定要下载，并且下在同一个文件夹，我是直接引用秋叶包的都不行，VAE也是非下不可。还有inswapper_128.onnx，直接调用ComfyUI\models\insightface的就行啦，本来硬盘就不够，况且这重复下载了，在其他插件中选模型时，也更麻烦。。一堆同名的，本来模型就够多的了，还是重复的。。文件管理再优化才行！

**Comment by THtianhao** [comment]
为了方便新手，只能牺牲一下大神了
