### ISSUE TITLE
PortraitEnhancement PM容易爆显存

### ISSUE THREAD

**Issue by oHuflying** [THtianhao/ComfyUI-Portrait-Maker#23]
在8G显存的3070上特别容易爆显存，在cry 显存显示上能看到VRAM一直处于67%以上，好像爆了一次后就会一直爆，是不是显存回收存在问题？同样的工作流，这个节点换做upscale_4x虽然慢，但是非常难发生爆显存，没有使用easyphoto，只使用了faceid和reactor。现在面部修复也去掉了，加上去还是爆。
bat启动参数有--lowvram，是否在显存上存在没有回收的情况呢。

**Comment by THtianhao** [comment]
是的呢，应该是显存不够，8G刚好是临界点，可以将工作流进行拆分，先做一部分，再做剩下的部分
