### ISSUE TITLE
Custom Nodes won't load with Standalone ComfyUI Installs

### ISSUE THREAD

**Issue by Kinglord** [THtianhao/ComfyUI-Portrait-Maker#3]
Hello,

This custom node won't load for ComfyUI users that are running the standalone version of ComfyUI. The requirements for ModelScope include a deprecated [aliyunsdkcore](https://github.com/duangy/aliyunsdkcore#aliyunsdkcore) which will not install with the bundled embedded python.

Hopefully this gets fixed soon, but until then anyone that wants to use this will need to setup a venv - unless there's another workaround I'm not aware of!

**Comment by THtianhao** [comment]
Sorry, the author of comfyui is also aware of this problem and has no intention of fixing it. We can only wait for modelscops to update, it is expected that their next version will solve this problem

**Comment by Kinglord** [comment]
Yip, I understand the dependency hell that python can cause first hand and understand it's out of your control. Hopefully it gets fixed soon!

**Comment by xiongbb** [comment]
Hopefully it gets fixed soon

**Comment by Gerkinfeltser** [comment]
To be clear, this is a symptom of the lack of ModelScope, correct? This is reported when loading the included workflow. Thanks!
![image](https://github.com/THtianhao/ComfyUI-Portrait-Maker/assets/1477787/90ffc069-15a3-4751-8faf-d057358ba3b4)

**Comment by THtianhao** [comment]
> To be clear, this is a symptom of the lack of ModelScope, correct? This is reported when loading the included workflow. Thanks!

Yes, this is an error caused by the lack of modelscope. You need to install the python environment manually instead of using the comfyui download package of windows.

**Comment by THtianhao** [comment]
resolve
