### ISSUE TITLE
Could we use some other face model 

### ISSUE THREAD

**Issue by ultimatech-cn** [THtianhao/ComfyUI-Portrait-Maker#7]
There are three models comparation as following, the first one is using by Portrait_maker
![1698020036382](https://github.com/THtianhao/ComfyUI-Portrait-Maker/assets/142652112/bd04e388-12c5-4ef0-9084-ed904d2dfcad)

**Comment by THtianhao** [comment]
This looks like this is an unnecessary process of controlnet, right?
